### ISSUE TITLE
Host on / Merge into jenkinsci

### ISSUE THREAD

**Issue by icnocop** [sankethpb/assemblyInfo-updater#1]
Hi.

Thank you for assemblyInfo-updater-plugin.

I'd like to request that this plugin get hosted on / merged into jenkinsci so that I can install and use this plugin from "Manage Plugins" within Jenkins.

Thank you.

**Comment by sankethpb** [comment]
@icnocop Apologies for so much delay, I hope you have found out to use Change Assembly Version Plugin instead. If you still need this, kindly let me know.
https://plugins.jenkins.io/change-assembly-version-plugin
